In [1]:
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
import numpy as np
def sigmoid(x):#激活函数
    return 1/(1+np.exp(-x))
input1 = np.array([[0.35],[0.9],[0.58],[0.78]]) #输入数据  4x1
w1 = np.random.rand(3,4)#第一层权重参数                                    3x4
w2 = np.random.rand(2,3)#第二层权重参数                                    2x3
real = np.array([[0.5],[0.7]])#标签
for s in range(100):
    output1 = sigmoid(np.dot(w1,input1))#第一层输出  3x1
    output2 = sigmoid(np.dot(w2,output1))#第二层输出,也即是最终输出    2x1
    cost = np.square(real-output2)/2#误差      2x1
    delta2=output2*(1-output2)*(real-output2)          #2x1
    delta1=output1*(1-output1)*w2.T.dot(delta2)      #3x1
    w2 = w2 + delta2.dot(output1.T)                        #2x3
    w1 = w1 + delta1.dot(input1.T)                         #3x4
    print(output1)
    print(output2)
    print(cost)
    print()




[[0.64503285]
 [0.81430744]
 [0.83203755]]
[[0.70871795]
 [0.86142234]]
[[0.02178159]
 [0.01302859]]
[[0.64163838]
 [0.81371317]
 [0.83026487]]
[[0.69214671]
 [0.85674788]]
[[0.01846018]
 [0.01228495]]
[[0.63845746]
 [0.81319395]
 [0.82858464]]
[[0.67604051]
 [0.85201573]]
[[0.01549513]
 [0.01155439]]
[[0.63549106]
 [0.8127418 ]
 [0.8270005 ]]
[[0.6605814 ]
 [0.84723581]]
[[0.01289319]
 [0.01083919]]
[[0.63273471]
 [0.81234783]
 [0.82551317]]
[[0.64591382]
 [0.84241793]]
[[0.01064542]
 [0.01014143]]
[[0.6301798 ]
 [0.81200305]
 [0.82412097]]
[[0.632141  ]
 [0.83757199]]
[[0.00873062]
 [0.00946303]]
[[0.62781485]
 [0.81169888]
 [0.82282044]]
[[0.61932588]
 [0.83270808]]
[[0.00711933]
 [0.00880572]]
[[0.62562682]
 [0.81142764]
 [0.82160691]]
[[0.60749535]
 [0.82783665]]
[[0.00577763]
 [0.0081711 ]]
[[0.62360211]
 [0.81118273]
 [0.82047507]]
[[0.59664633]
 [0.82296853]]
[[0.00467026]
 [0.00756063]]
[[0.62172732]
 [0.81095871]
 [0.81941935]]
[[0.58675255]
 [0.81811501]]
[[0.003763  ]
 [0.0

[[0.5971723 ]
 [0.80717884]
 [0.80489453]]
[[0.50000307]
 [0.70033015]]
[[4.71081669e-12]
 [5.44995409e-08]]
[[0.59716947]
 [0.80717813]
 [0.80489278]]
[[0.50000259]
 [0.70030561]]
[[3.34488070e-12]
 [4.66988257e-08]]
[[0.59716684]
 [0.80717747]
 [0.80489115]]
[[0.50000217]
 [0.70028289]]
[[2.34563652e-12]
 [4.00141537e-08]]
[[0.59716441]
 [0.80717685]
 [0.80488965]]
[[0.5000018 ]
 [0.70026186]]
[[1.62086879e-12]
 [3.42859582e-08]]
[[0.59716217]
 [0.80717628]
 [0.80488826]]
[[0.50000148]
 [0.70024239]]
[[1.10042181e-12]
 [2.93774649e-08]]
[[0.59716009]
 [0.80717576]
 [0.80488697]]
[[0.50000121]
 [0.70022437]]
[[7.31118486e-13]
 [2.51714404e-08]]
[[0.59715816]
 [0.80717527]
 [0.80488578]]
[[0.50000097]
 [0.70020769]]
[[4.72816153e-13]
 [2.15674044e-08]]
